version: '3.8'

services:
  postgres:
    image: postgres
    container_name: medical_appointment
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: coti
      POSTGRES_DB: medical_appointment  # 👈 Aqui define o nome do banco
    volumes:
      - medical_data:/var/lib/postgresql/data
    restart: always

volumes:
  medical_data:
    name: medical_data
