version: '3.8'
services:
  postgres:
    image: postgres
    container_name: medical_appointment
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: coti
    restart: always